services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3012:3000
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    environment:
      HOMEPAGE_ALLOWED_HOSTS: gethomepage.dev,dashboard.tomvargasd.site,localhost:3012
      PUID: $PUID
      PGID: $PGID