---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background:
  image: /images/bg-eva01.jpg
  blur: sm 
  saturate: 50 
  brightness: 50 
  opacity: 50 
