---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

background: https://image-5.uhdpaper.com/wallpaper/evangelion-mecha-hd-wallpaper-uhdpaper.com-494@5@e.jpg
